# Generated by Django 5.0.1 on 2024-01-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_sales',
            field=models.IntegerField(default=0, verbose_name='Кол-во продаж'),
        ),
    ]
